name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore GHelperAutoProfileSwitcher.csproj
      
    - name: Publish
      run: dotnet publish GHelperAutoProfileSwitcher.csproj --no-restore --configuration Release -o ./publish
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GHelperAutoProfileSwitcher
        path: ./publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: GHelperAutoProfileSwitcher
        path: ./publish/
        
    - name: Zip files
      run: |
        cd publish
        zip -r ../GHelperAutoProfileSwitcher.zip ./*
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: GHelperAutoProfileSwitcher.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
